server:
  port : ${PORT:8080}

spring:
  cloud:
    gateway:
      routes:
      - id: produtos
        uri: lb://erp-produto
        predicates:
        - Method=GET,POST,PUT
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://192.168.1.169:8761/eureka}

# ACTUATOR
management:
  endpoint:
    health:
      enabled: true
      show-details: always
    info:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    jmx:
      exposure:
        include: "*"
    web:
      exposure:
        include: "*"
    base-path: "/actuator"
    cors:
      allowed-origins: true
    enabled-by-default: false
