server:
  port : ${PORT:8081}

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
      - id: produtos
          uri: lb://ERP-PRODUTO
          predicates:
          - Method=GET

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://192.168.1.169:8761/eureka}
    register-with-eureka: true
    fetchRegistry: true
    instance:
      preferIpAddress: true

management:
  endpoint:
    health:
      enabled: true
      show-details: always
    info:
      enabled: true
    prometheus:
      enabled: true
    refresh:
      enabled: true
      show-details: always
    gateway:
      enabled: true
      show-details: always
  endpoints:
    jmx:
      exposure:
        include: "*"
    web:
      exposure:
        include: "*"
    base-path: "/actuator"
    cors:
      allowed-origins: true
    enabled-by-default: true

