server:
  port : ${PORT:8810}

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://172.17.0.1:8761/eureka}
  instance:
    preferIpAddress: true

spring:
  # Database
  datasource:
    url: jdbc:postgresql://172.17.0.1:5432/produto
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
  # JPA properties
  jpa:
    hibernate:
      ddl-auto: create # When you launch the application for the first time - switch "none" at "create"
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true

# ACTUATOR
management:
  endpoint:
    health:
      enabled: true
      show-details: always
    info:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    jmx:
      exposure:
        include: "*"
    web:
      exposure:
        include: "*"
    base-path: "/actuator"
    cors:
      allowed-origins: true
    enabled-by-default: false
